# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class ClearExpiredOrdersParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    orderId: str
    orderType: str


class ClearExpiredOrdersParameter(RootModel[List[ClearExpiredOrdersParameterItem]]):
    root: List[ClearExpiredOrdersParameterItem]
