# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PauseParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entrypoint: str
    pauseBool: bool


class PauseParameter(RootModel[List[PauseParameterItem]]):
    root: List[PauseParameterItem]
