# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PermitPlaceBuyOrderItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rwaTokenAmount: str
    pricePerRwaToken: str
    currency: str
    orderExpiry: str | None = None
    isMarketOrder: bool


class Action(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitPlaceBuyOrder: List[PermitPlaceBuyOrderItem]


class PermitPlaceSellOrderItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rwaTokenAmount: str
    pricePerRwaToken: str
    currency: str
    orderExpiry: str | None = None
    isMarketOrder: bool


class Action1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitPlaceSellOrder: List[PermitPlaceSellOrderItem]


class PermitCancelOrder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    orderId: str
    orderType: str


class Action2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitCancelOrders: List[PermitCancelOrder]


class PermitProcessRefundItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    orderId: str
    orderType: str


class Action3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitProcessRefund: List[PermitProcessRefundItem]


class PermitSetPermitExpiryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userAddress: str
    expirySeconds: str
    permitHash: str | None = None


class Action4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitSetPermitExpiry: List[PermitSetPermitExpiryItem]


class PermitAndExecuteParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userPublicKey: str
    userSignature: str
    action: Action | Action1 | Action2 | Action3 | Action4
    deadline: str


class PermitAndExecuteParameter(RootModel[List[PermitAndExecuteParameterItem]]):
    root: List[PermitAndExecuteParameterItem]
