# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PlaceSellOrderParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rwaTokenAmount: str
    pricePerRwaToken: str
    currency: str
    orderExpiry: str | None = None


class PlaceSellOrderParameter(RootModel[List[PlaceSellOrderParameterItem]]):
    root: List[PlaceSellOrderParameterItem]
