# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PlaceBuyOrderParameterItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rwaTokenAmount: str
    pricePerRwaToken: str
    currency: str
    orderExpiry: str | None = None


class PlaceBuyOrderParameter(RootModel[List[PlaceBuyOrderParameterItem]]):
    root: List[PlaceBuyOrderParameterItem]
