# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Token(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tokenContractAddress: str
    tokenId: str


class SetCurrencyParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actionType: str
    name: str
    decimals: str
    token: Token
