# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class TransferFeesParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    receiver: str
    currencySet: List[str]
