# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PermitSetPermitExpiryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userAddress: str
    expirySeconds: str
    permitHash: str | None = None


class Action(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitSetPermitExpiry: List[PermitSetPermitExpiryItem]


class Tx(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    to_: str
    token_id: str
    amount: str


class PermitTransferItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: str
    txs: List[Tx]


class Action1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitTransfer: List[PermitTransferItem]


class AddOperator(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    owner: str
    operator: str
    token_id: str


class PermitUpdateOperators(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    add_operator: AddOperator


class RemoveOperator(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    owner: str
    operator: str
    token_id: str


class PermitUpdateOperators1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    remove_operator: RemoveOperator


class Action2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitUpdateOperators: List[PermitUpdateOperators | PermitUpdateOperators1]


class PermitAndExecuteParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userPublicKey: str
    userSignature: str
    action: Action | Action1 | Action2


class PermitAndExecuteParameter(RootModel[List[PermitAndExecuteParameterItem]]):
    root: List[PermitAndExecuteParameterItem]
