indexes:
  kyc:
    kind: tezos.operations
    datasources:
    - mvkt_atlasnet
    contracts:
    - kyc
    types:
    - origination
    - transaction
    handlers:
    - callback: kyc.origination
      pattern:
      - type: origination
        originated_contract: kyc
    - callback: kyc.update_metadata
      pattern:
      - destination: kyc
        entrypoint: updateMetadata
    - callback: kyc.set_super_admin
      pattern:
      - destination: kyc
        entrypoint: setSuperAdmin
    - callback: kyc.claim_super_admin
      pattern:
      - destination: kyc
        entrypoint: claimSuperAdmin
    - callback: kyc.set_lambda
      pattern:
      - destination: kyc
        entrypoint: setLambda
    - callback: kyc.toggle_pause_entrypoint
      pattern:
      - destination: kyc
        entrypoint: togglePauseEntrypoint
    - callback: kyc.set_country_transfer_rule
      pattern:
      - destination: kyc
        entrypoint: setCountryTransferRule
    - callback: kyc.set_kyc_registrar
      pattern:
      - destination: kyc
        entrypoint: setKycRegistrar
    - callback: kyc.pause_kyc_registrar
      pattern:
      - destination: kyc
        entrypoint: pauseKycRegistrar
    - callback: kyc.set_valid_input
      pattern:
      - destination: kyc
        entrypoint: setValidInput
    - callback: kyc.set_whitelist
      pattern:
      - destination: kyc
        entrypoint: setWhitelist
    - callback: kyc.set_blacklist
      pattern:
      - destination: kyc
        entrypoint: setBlacklist
    - callback: kyc.set_member
      pattern:
      - destination: kyc
        entrypoint: setMember
    - callback: kyc.set_registrar_admin
      pattern:
      - destination: kyc
        entrypoint: setRegistrarAdmin
    - callback: kyc.freeze_member
      pattern:
      - destination: kyc
        entrypoint: freezeMember
    - callback: kyc.unfreeze_member
      pattern:
      - destination: kyc
        entrypoint: unfreezeMember
  orderbook:
    kind: tezos.operations
    datasources:
    - mvkt_atlasnet
    contracts:
    - mars1_orderbook
    types:
    - origination
    - transaction
    handlers:
    - callback: orderbook.origination
      pattern:
      - type: origination
        originated_contract: mars1_orderbook
    - callback: orderbook.set_lambda
      pattern:
      - destination: mars1_orderbook
        entrypoint: setLambda
    - callback: orderbook.set_currency
      pattern:
      - destination: mars1_orderbook
        entrypoint: setCurrency
    - callback: orderbook.set_super_admin
      pattern:
      - destination: mars1_orderbook
        entrypoint: setSuperAdmin
    - callback: orderbook.set_kyc_address
      pattern:
      - destination: mars1_orderbook
        entrypoint: setKycAddress
    - callback: orderbook.claim_super_admin
      pattern:
      - destination: mars1_orderbook
        entrypoint: claimSuperAdmin
    - callback: orderbook.update_metadata
      pattern:
      - destination: mars1_orderbook
        entrypoint: updateMetadata
    - callback: orderbook.update_config
      pattern:
      - destination: mars1_orderbook
        entrypoint: updateConfig
    - callback: orderbook.toggle_pause_entrypoint
      pattern:
      - destination: mars1_orderbook
        entrypoint: togglePauseEntrypoint
    - callback: orderbook.transfer_fees
      pattern:
      - destination: mars1_orderbook
        entrypoint: transferFees
    - callback: orderbook.clear_expired_orders
      pattern:
      - destination: mars1_orderbook
        entrypoint: clearExpiredOrders
    - callback: orderbook.match_orders
      pattern:
      - destination: mars1_orderbook
        entrypoint: matchOrders
    - callback: orderbook.place_buy_order
      pattern:
      - destination: mars1_orderbook
        entrypoint: placeBuyOrder
    - callback: orderbook.place_sell_order
      pattern:
      - destination: mars1_orderbook
        entrypoint: placeSellOrder
    - callback: orderbook.cancel_orders
      pattern:
      - destination: mars1_orderbook
        entrypoint: cancelOrders
    - callback: orderbook.process_refund
      pattern:
      - destination: mars1_orderbook
        entrypoint: processRefund
  dodo_mav:
    kind: tezos.operations
    datasources:
    - mvkt_atlasnet
    contracts:
    - mars1_dodo_mav
    types:
    - origination
    - transaction
    handlers:
    - callback: dodo_mav.origination
      pattern:
      - type: origination
        originated_contract: mars1_dodo_mav
    - callback: dodo_mav.set_lambda
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: setLambda
    - callback: dodo_mav.set_super_admin
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: setSuperAdmin
    - callback: dodo_mav.claim_super_admin
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: claimSuperAdmin
    - callback: dodo_mav.set_guide_price
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: setGuidePrice
    - callback: dodo_mav.update_guide_price
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: updateGuidePrice
    - callback: dodo_mav.update_metadata
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: updateMetadata
    - callback: dodo_mav.update_config
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: updateConfig
    - callback: dodo_mav.toggle_pause_entrypoint
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: togglePauseEntrypoint
    - callback: dodo_mav.buy_base_token
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: buyBaseToken
      - type: transaction
        alias: base_token_transfer
        destination: base_token
        entrypoint: transfer
      - type: transaction
        alias: quote_token_transfer
        destination: quote_token
        entrypoint: transfer
      - type: transaction
        alias: maintainer_fee
        destination: base_token
        entrypoint: transfer
        optional: True
    - callback: dodo_mav.sell_base_token
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: sellBaseToken
      - type: transaction
        alias: quote_token_transfer
        destination: quote_token
        entrypoint: transfer
      - type: transaction
        alias: base_token_transfer
        destination: base_token
        entrypoint: transfer
      - type: transaction
        alias: maintainer_fee
        destination: quote_token
        entrypoint: transfer
        optional: True
    - callback: dodo_mav.withdraw_quote_token
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: withdrawQuoteToken
    - callback: dodo_mav.withdraw_base_token
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: withdrawBaseToken
    - callback: dodo_mav.withdraw_all_quote_tokens
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: withdrawAllQuoteTokens
    - callback: dodo_mav.withdraw_all_base_tokens
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: withdrawAllBaseTokens
    - callback: dodo_mav.deposit_quote_token
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: depositQuoteToken
    - callback: dodo_mav.deposit_base_token
      pattern:
      - destination: mars1_dodo_mav
        entrypoint: depositBaseToken
  # marketplace:
  #   kind: tezos.operations
  #   datasources:
  #   - mvkt_atlasnet
  #   contracts:
  #   - marketplace
  #   types:
  #   - origination
  #   - transaction
  #   handlers:
  #   - callback: marketplace.origination
  #     pattern:
  #     - type: origination
  #       originated_contract: marketplace
  #   - callback: marketplace.set_lambda
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: setLambda
  #   - callback: marketplace.set_super_admin
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: setSuperAdmin
  #   - callback: marketplace.claim_super_admin
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: claimSuperAdmin
  #   - callback: marketplace.update_metadata
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: updateMetadata
  #   - callback: marketplace.update_config
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: updateConfig
  #   - callback: marketplace.update_whitelist_contracts
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: updateWhitelistContracts
  #   - callback: marketplace.update_general_contracts
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: updateGeneralContracts
  #   - callback: marketplace.pause_all
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: pauseAll
  #   - callback: marketplace.unpause_all
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: unpauseAll
  #   - callback: marketplace.toggle_pause_entrypoint
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: togglePauseEntrypoint
  #   - callback: marketplace.set_currency
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: setCurrency
  #   - callback: marketplace.create_listing
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: createListing
  #   - callback: marketplace.edit_listing
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: editListing
  #   - callback: marketplace.remove_listing
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: removeListing
  #   - callback: marketplace.purchase
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: purchase
  #   - callback: marketplace.offer
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: offer
  #   - callback: marketplace.accept_offer
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: acceptOffer
  #   - callback: marketplace.remove_offer
  #     pattern:
  #     - destination: marketplace
  #       entrypoint: removeOffer
  super_admin:
    kind: tezos.operations
    datasources:
    - mvkt_atlasnet
    contracts:
    - super_admin
    types:
    - origination
    - transaction
    handlers:
    - callback: super_admin.origination
      pattern:
      - type: origination
        originated_contract: super_admin
    - callback: super_admin.set_lambda
      pattern:
      - destination: super_admin
        entrypoint: setLambda
    - callback: super_admin.set_super_admin
      pattern:
      - destination: super_admin
        entrypoint: setSuperAdmin
    - callback: super_admin.claim_super_admin
      pattern:
      - destination: super_admin
        entrypoint: claimSuperAdmin
    - callback: super_admin.update_metadata
      pattern:
      - destination: super_admin
        entrypoint: updateMetadata
    - callback: super_admin.set_general_admin
      pattern:
      - destination: super_admin
        entrypoint: setGeneralAdmin
    - callback: super_admin.remove_general_admin
      pattern:
      - destination: super_admin
        entrypoint: removeGeneralAdmin
    - callback: super_admin.set_contract_admin
      pattern:
      - destination: super_admin
        entrypoint: setContractAdmin
    - callback: super_admin.remove_contract_admin
      pattern:
      - destination: super_admin
        entrypoint: removeContractAdmin
    - callback: super_admin.update_config
      pattern:
      - destination: super_admin
        entrypoint: updateConfig
    - callback: super_admin.add_signatory
      pattern:
      - destination: super_admin
        entrypoint: addSignatory
    - callback: super_admin.remove_signatory
      pattern:
      - destination: super_admin
        entrypoint: removeSignatory
    - callback: super_admin.set_token_kyc_address
      pattern:
      - destination: super_admin
        entrypoint: setTokenKycAddress
    - callback: super_admin.kill_token
      pattern:
      - destination: super_admin
        entrypoint: killToken
    - callback: super_admin.flush_action
      pattern:
      - destination: super_admin
        entrypoint: flushAction
    - callback: super_admin.sign_action
      pattern:
      - destination: super_admin
        entrypoint: signAction
  fa2_balances:
    kind: tezos.token_balances
    datasources:
      - mvkt_atlasnet
    handlers:
      - callback: misc.on_balance_update
        contract: fa2
  fa2_transfers:
    kind: tezos.token_transfers
    datasources:
      - mvkt_atlasnet
    handlers:
      - callback: misc.on_token_transfer
        contract: fa2

hooks:
  refresh_tokens:
    callback: refresh_tokens
    atomic: False

jobs:
  refresh_tokens:
    hook: refresh_tokens
    interval: 300
