indexes:
  mars1_orderbook:
    template: orderbook_template
    values:
      orderbook_contract: mars1_orderbook
  ocean_orderbook:
    template: orderbook_template
    values:
      orderbook_contract: ocean_orderbook
  queen_orderbook:
    template: orderbook_template
    values:
      orderbook_contract: queen_orderbook
  ntbm_orderbook:
    template: orderbook_template
    values:
      orderbook_contract: ntbm_orderbook
  kyc:
    kind: tezos.operations
    datasources:
    - mvkt_atlasnet
    contracts:
    - kyc
    types:
    - origination
    - transaction
    handlers:
    - callback: kyc.origination
      pattern:
      - type: origination
        originated_contract: kyc
    - callback: kyc.update_metadata
      pattern:
      - destination: kyc
        entrypoint: updateMetadata
    - callback: kyc.set_super_admin
      pattern:
      - destination: kyc
        entrypoint: setSuperAdmin
    - callback: kyc.claim_super_admin
      pattern:
      - destination: kyc
        entrypoint: claimSuperAdmin
    - callback: kyc.set_lambda
      pattern:
      - destination: kyc
        entrypoint: setLambda
    - callback: kyc.toggle_pause_entrypoint
      pattern:
      - destination: kyc
        entrypoint: togglePauseEntrypoint
    - callback: kyc.set_country_transfer_rule
      pattern:
      - destination: kyc
        entrypoint: setCountryTransferRule
    - callback: kyc.set_kyc_registrar
      pattern:
      - destination: kyc
        entrypoint: setKycRegistrar
    - callback: kyc.pause_kyc_registrar
      pattern:
      - destination: kyc
        entrypoint: pauseKycRegistrar
    - callback: kyc.set_valid_input
      pattern:
      - destination: kyc
        entrypoint: setValidInput
    - callback: kyc.set_whitelist
      pattern:
      - destination: kyc
        entrypoint: setWhitelist
    - callback: kyc.set_blacklist
      pattern:
      - destination: kyc
        entrypoint: setBlacklist
    - callback: kyc.set_member
      pattern:
      - destination: kyc
        entrypoint: setMember
    - callback: kyc.set_registrar_admin
      pattern:
      - destination: kyc
        entrypoint: setRegistrarAdmin
    - callback: kyc.freeze_member
      pattern:
      - destination: kyc
        entrypoint: freezeMember
    - callback: kyc.unfreeze_member
      pattern:
      - destination: kyc
        entrypoint: unfreezeMember
  super_admin:
    kind: tezos.operations
    datasources:
    - mvkt_atlasnet
    contracts:
    - super_admin
    types:
    - origination
    - transaction
    handlers:
    - callback: super_admin.origination
      pattern:
      - type: origination
        originated_contract: super_admin
    - callback: super_admin.set_lambda
      pattern:
      - destination: super_admin
        entrypoint: setLambda
    - callback: super_admin.set_super_admin
      pattern:
      - destination: super_admin
        entrypoint: setSuperAdmin
    - callback: super_admin.claim_super_admin
      pattern:
      - destination: super_admin
        entrypoint: claimSuperAdmin
    - callback: super_admin.update_metadata
      pattern:
      - destination: super_admin
        entrypoint: updateMetadata
    - callback: super_admin.set_general_admin
      pattern:
      - destination: super_admin
        entrypoint: setGeneralAdmin
    - callback: super_admin.remove_general_admin
      pattern:
      - destination: super_admin
        entrypoint: removeGeneralAdmin
    - callback: super_admin.set_contract_admin
      pattern:
      - destination: super_admin
        entrypoint: setContractAdmin
    - callback: super_admin.remove_contract_admin
      pattern:
      - destination: super_admin
        entrypoint: removeContractAdmin
    - callback: super_admin.update_config
      pattern:
      - destination: super_admin
        entrypoint: updateConfig
    - callback: super_admin.add_signatory
      pattern:
      - destination: super_admin
        entrypoint: addSignatory
    - callback: super_admin.remove_signatory
      pattern:
      - destination: super_admin
        entrypoint: removeSignatory
    - callback: super_admin.set_token_kyc_address
      pattern:
      - destination: super_admin
        entrypoint: setTokenKycAddress
    - callback: super_admin.kill_token
      pattern:
      - destination: super_admin
        entrypoint: killToken
    - callback: super_admin.flush_action
      pattern:
      - destination: super_admin
        entrypoint: flushAction
    - callback: super_admin.sign_action
      pattern:
      - destination: super_admin
        entrypoint: signAction

templates:
  # fa2_balances_template:
  #   kind: tezos.token_balances
  #   datasources:
  #     - mvkt_atlasnet
  #   handlers:
  #     - callback: misc.on_balance_update
  #       contract: <fa2_contract>
  # fa2_transfers_template:
  #   kind: tezos.token_transfers
  #   datasources:
  #     - mvkt_atlasnet
  #   handlers:
  #     - callback: misc.on_token_transfer
  #       contract: <fa2_contract> 
  orderbook_template:
    kind: tezos.operations
    datasources:
    - mvkt_atlasnet
    contracts:
    - <orderbook_contract>
    types:
    - origination
    - transaction
    handlers:
    - callback: orderbook.origination
      pattern:
      - type: origination
        originated_contract: <orderbook_contract>
    - callback: orderbook.set_lambda
      pattern:
      - destination: <orderbook_contract>
        entrypoint: setLambda
    - callback: orderbook.set_currency
      pattern:
      - destination: <orderbook_contract>
        entrypoint: setCurrency
    - callback: orderbook.set_super_admin
      pattern:
      - destination: <orderbook_contract>
        entrypoint: setSuperAdmin
    - callback: orderbook.set_kyc_address
      pattern:
      - destination: <orderbook_contract>
        entrypoint: setKycAddress
    - callback: orderbook.claim_super_admin
      pattern:
      - destination: <orderbook_contract>
        entrypoint: claimSuperAdmin
    - callback: orderbook.update_metadata
      pattern:
      - destination: <orderbook_contract>
        entrypoint: updateMetadata
    - callback: orderbook.update_config
      pattern:
      - destination: <orderbook_contract>
        entrypoint: updateConfig
    - callback: orderbook.toggle_pause_entrypoint
      pattern:
      - destination: <orderbook_contract>
        entrypoint: togglePauseEntrypoint
    - callback: orderbook.transfer_fees
      pattern:
      - destination: <orderbook_contract>
        entrypoint: transferFees
    - callback: orderbook.clear_expired_orders
      pattern:
      - destination: <orderbook_contract>
        entrypoint: clearExpiredOrders
    - callback: orderbook.match_orders
      pattern:
      - destination: <orderbook_contract>
        entrypoint: matchOrders
    - callback: orderbook.place_buy_order
      pattern:
      - destination: <orderbook_contract>
        entrypoint: placeBuyOrder
    - callback: orderbook.place_sell_order
      pattern:
      - destination: <orderbook_contract>
        entrypoint: placeSellOrder
    - callback: orderbook.cancel_orders
      pattern:
      - destination: <orderbook_contract>
        entrypoint: cancelOrders
    - callback: orderbook.process_refund
      pattern:
      - destination: <orderbook_contract>
        entrypoint: processRefund

hooks:
  refresh_tokens:
    callback: refresh_tokens
    atomic: False

jobs:
  refresh_tokens:
    hook: refresh_tokens
    interval: 600
