# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class AllowedMembershipTiers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    minPurchaseAmount: str | None = None
    maxAmountPerWalletTotal: str | None = None


class Currency(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tokenContractAddress: str
    tokenId: str


class Currency1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fa2: Fa2


class Currency2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mav: Dict[str, Any]


class Payments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    price: str
    currency: Currency | Currency1 | Currency2


class SaleOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    totalBought: str
    maxAmountCap: str | None = None
    allowedMembershipTiers: Dict[str, AllowedMembershipTiers]
    payments: Dict[str, Payments]
    isPaused: bool
    saleStart: str | None = None
    saleEnd: str | None = None


class LaunchLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    isPaused: bool
    purchaseFeePercent: str
    status: str
    tokenIssuanceType: str
    tokenDistributionType: str
    tokenContractAddress: str
    tokenId: str
    maxAmountCap: str
    totalBought: str
    saleStart: str
    saleEnd: str | None = None
    saleClosed: str | None = None
    saleOptions: Dict[str, SaleOptions]


class Key(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    string: str
    address: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    purchased: Dict[str, str]
    totalPurchased: str
    totalDistributed: str


class PurchaseLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: Value


class LaunchpadStorage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    superAdmin: str
    newSuperAdmin: str | None = None
    membershipKycAddress: str
    treasuryLedger: Dict[str, str]
    metadata: Dict[str, str]
    pauseLedger: Dict[str, bool]
    launchLedger: Dict[str, LaunchLedger]
    purchaseLedger: List[PurchaseLedgerItem]
    lambdaLedger: Dict[str, str]
