# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    quantityTickSize: str
    priceTickSize: str
    maxOrdersPerPriceLevel: str
    minExpiryTime: str
    minTimeBeforeClosingOrder: str
    minBuyOrderAmount: str
    minBuyOrderValue: str
    minSellOrderAmount: str
    minSellOrderValue: str
    buyOrderFee: str
    sellOrderFee: str
    cancelOrderFee: str
    lowerBoundBuyOrderPercent: str
    upperBoundBuyOrderPercent: str
    lowerBoundSellOrderPercent: str
    upperBoundSellOrderPercent: str
    permitDefaultExpiryDuration: str
    permitMaxExpiryDuration: str


class FeeLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nat_0: str
    nat_1: str


class CurrencyLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tokenContractAddress: str
    tokenId: str
    decimals: str


class TotalOrderFulfilled(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nat_0: str
    nat_1: str


class Booleans(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bool_0: bool
    bool_1: bool
    bool_2: bool


class OrderTimestamps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    timestamp_0: str
    timestamp_1: str | None = None


class BuyOrderLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    initiator: str
    rwaTokenAmount: str
    pricePerRwaToken: str
    currency: str
    fulfilledAmount: str
    unfulfilledAmount: str
    totalOrderFulfilled: TotalOrderFulfilled
    booleans: Booleans
    isRefunded: bool
    refundedAmount: str
    orderExpiry: str | None = None
    orderTimestamps: OrderTimestamps
    isMarketOrder: bool


class SellOrderLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    initiator: str
    rwaTokenAmount: str
    pricePerRwaToken: str
    currency: str
    fulfilledAmount: str
    unfulfilledAmount: str
    totalOrderFulfilled: TotalOrderFulfilled
    booleans: Booleans
    isRefunded: bool
    refundedAmount: str
    orderExpiry: str | None = None
    orderTimestamps: OrderTimestamps
    isMarketOrder: bool


class BuyOrderMap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    headCounter: str
    nextCounter: str
    sortedOrderMap: Dict[str, str]
    orderToCounterMap: Dict[str, str]


class SellOrderMap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    headCounter: str
    nextCounter: str
    sortedOrderMap: Dict[str, str]
    orderToCounterMap: Dict[str, str]


class HighestBuyPrice(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    orderId: str
    price: str
    marketOrderExists: bool


class LowestSellPrice(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    orderId: str
    price: str
    marketOrderExists: bool


class LastMatchedPrice(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    price: str
    lastMatchedTimestamp: str


class Key(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address: str
    bytes: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    registeredAt: str
    deadline: str


class PermitsLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: Value


class PermitsExpiryLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: str


class OrderbookStorage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    superAdmin: str
    newSuperAdmin: str | None = None
    rwaTokenAddress: str
    rwaTokenDecimals: str
    membershipKycAddress: str
    metadata: Dict[str, str]
    config: Config
    pauseLedger: Dict[str, bool]
    feeLedger: Dict[str, FeeLedger]
    currencyLedger: Dict[str, CurrencyLedger]
    buyOrderLedger: Dict[str, BuyOrderLedger]
    sellOrderLedger: Dict[str, SellOrderLedger]
    buyPriceMap: Dict[str, str]
    sellPriceMap: Dict[str, str]
    buyOrderMap: Dict[str, BuyOrderMap]
    sellOrderMap: Dict[str, SellOrderMap]
    highestBuyPrice: HighestBuyPrice
    lowestSellPrice: LowestSellPrice
    lastMatchedPrice: LastMatchedPrice
    buyOrderCounter: str
    sellOrderCounter: str
    lambdaLedger: Dict[str, str]
    permitsLedger: List[PermitsLedgerItem]
    permitsCounterLedger: Dict[str, str]
    permitsExpiryLedger: List[PermitsExpiryLedgerItem]
    userPermitsExpiryLedger: Dict[str, str]
