# generated by DipDup 8.4.2; relaxed for TZKT (big map ids vs expanded)

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class TokenMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token_id: str
    token_info: Dict[str, str]


class Key(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address_0: str
    address_1: str
    nat: str


class Operator(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: Dict[str, Any]


class QuoteTokenStorage(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )

    admin: str | None = None
    governanceAddress: str | None = None
    totalSupply: str | None = None
    metadata: int | Dict[str, Any] | None = None
    token_metadata: int | Dict[str, Any] | None = None
    ledger: int | Dict[str, Any] | List[Any] | None = None
    operators: int | List[Operator] | None = None
    whitelistContracts: int | Dict[str, Dict[str, Any]] | Dict[str, Any] | None = None
