# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class BuyBaseTokenParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: str
    minMaxQuote: str
