# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class WithdrawAllBaseTokensParameter(BaseModel):
    pass
    model_config = ConfigDict(
        extra="forbid",
    )
