# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    threshold: str
    actionExpiryInSeconds: str


class SignatoryActionLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    initiator: str
    actionType: str
    executed: bool
    status: str
    signersCount: str
    signers: List[str]
    dataMap: Dict[str, str]
    startDateTime: str
    startLevel: str
    executedDateTime: str | None = None
    executedLevel: str | None = None
    expirationDateTime: str


class Key(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address_0: str
    string: str
    address_1: str


class UserRoleLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: Dict[str, Any]


class SuperAdminStorage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata: Dict[str, str]
    baker: str | None = None
    config: Config
    signatoryLedger: Dict[str, Dict[str, Any]]
    signatorySize: str
    signatoryActionLedger: Dict[str, SignatoryActionLedger]
    actionCounter: str
    userRoleLedger: List[UserRoleLedgerItem]
    lambdaLedger: Dict[str, str]
