# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class LedgerKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    owner: str
    token_id: str
