# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class AllowedMembershipTiers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    minPurchaseAmount: str | None = None
    maxAmountPerWalletTotal: str | None = None


class Currency(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tokenContractAddress: str
    tokenId: str


class Currency1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fa2: Fa2


class Currency2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mav: Dict[str, Any]


class Payments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    price: str
    currency: Currency | Currency1 | Currency2


class SaleOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    totalBought: str
    maxAmountCap: str | None = None
    allowedMembershipTiers: Dict[str, AllowedMembershipTiers]
    payments: Dict[str, Payments]
    isPaused: bool
    saleStart: str | None = None
    saleEnd: str | None = None


class CreateTokenLaunchParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launchName: str
    purchaseFeePercent: str
    tokenIssuanceType: str
    tokenDistributionType: str
    tokenContractAddress: str
    tokenId: str
    maxAmountCap: str
    saleStart: str
    saleEnd: str | None = None
    saleOptions: Dict[str, SaleOptions]
