# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class DistributeTokensParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userAddress: str
    launchName: str


class DistributeTokensParameter(RootModel[List[DistributeTokensParameterItem]]):
    root: List[DistributeTokensParameterItem]
