# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PermitPurchase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launchName: str
    amount: str
    saleOption: str
    payment: str
    maxTotalPayment: str


class Action(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitPurchase: PermitPurchase


class PermitSetPermitExpiryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userAddress: str
    expirySeconds: str
    permitHash: str | None = None


class Action1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitSetPermitExpiry: List[PermitSetPermitExpiryItem]


class PermitAndExecuteParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userPublicKey: str
    userSignature: str
    action: Action | Action1
    deadline: str


class PermitAndExecuteParameter(RootModel[List[PermitAndExecuteParameterItem]]):
    root: List[PermitAndExecuteParameterItem]
