# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PurchaseParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launchName: str
    amount: str
    saleOption: str
    payment: str
