# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class SetPurchaseRecordParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launchName: str
    amount: str
    saleOption: str
    purchaser: str
    payment: str


class SetPurchaseRecordParameter(RootModel[List[SetPurchaseRecordParameterItem]]):
    root: List[SetPurchaseRecordParameterItem]
