# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict, RootModel


class AllowedMembershipTiers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    minPurchaseAmount: str | None = None
    maxAmountPerWalletTotal: str | None = None


class Currency(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tokenContractAddress: str
    tokenId: str


class Currency1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fa2: Fa2


class Currency2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mav: Dict[str, Any]


class Payments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    price: str
    currency: Currency | Currency1 | Currency2


class CreateNewSaleOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launchName: str
    saleOption: str
    maxAmountCap: str | None = None
    allowedMembershipTiers: Dict[str, AllowedMembershipTiers]
    payments: Dict[str, Payments]
    isPaused: bool
    saleStart: str | None = None
    saleEnd: str | None = None


class SetSaleOptionParameter1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    createNewSaleOption: CreateNewSaleOption


class Currency3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fa12: str


class Currency4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fa2: Fa2


class Currency5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mav: Dict[str, Any]


class Payments1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    price: str
    currency: Currency3 | Currency4 | Currency5


class UpdateSaleOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launchName: str
    saleOption: str
    totalBought: str | None = None
    maxAmountCap: str | None = None
    allowedMembershipTiers: Dict[str, AllowedMembershipTiers] | None = None
    payments: Dict[str, Payments1] | None = None
    isPaused: bool | None = None
    saleStart: str | None = None
    saleEnd: str | None = None


class SetSaleOptionParameter2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    updateSaleOption: UpdateSaleOption


class SetSaleOptionParameter(
    RootModel[SetSaleOptionParameter1 | SetSaleOptionParameter2]
):
    root: SetSaleOptionParameter1 | SetSaleOptionParameter2
