# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class SetLaunchStatusParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launchName: str
    launchStatus: str
