# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class SetTreasuryParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    treasuryName: str
    treasuryAddress: str
