# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitDefaultExpiryDuration: str
    permitMaxExpiryDuration: str


class TokenMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token_id: str
    token_info: Dict[str, str]


class Key(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address_0: str
    address_1: str
    nat: str


class Operator(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: Dict[str, Any]


class Key1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address: str
    bytes: str


class PermitsLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key1
    value: str


class PermitsExpiryLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key1
    value: str


class WusdtStorage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    superAdmin: str
    newSuperAdmin: str | None = None
    minterBridgeSet: List[str]
    metadata: Dict[str, str]
    config: Config
    token_metadata: Dict[str, TokenMetadata]
    total_supply: str
    ledger: Dict[str, str]
    operators: List[Operator]
    permitsLedger: List[PermitsLedgerItem]
    permitsCounterLedger: Dict[str, str]
    permitsExpiryLedger: List[PermitsExpiryLedgerItem]
    userPermitsExpiryLedger: Dict[str, str]
