# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class TokenMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_id: str
    token_info: Dict[str, str]


class UserChunkLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chunkCounter: str
    snapshotCounter: str


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat_0: str
    address: str
    nat_1: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    timestamp: str


class SnapshotLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Dict[str, Value]


class Key1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str
    token_id: str


class LedgerItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key1
    value: str


class Key2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address_0: str
    address_1: str
    nat: str


class Operator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key2
    value: Dict[str, Any]


class BaseTokenStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    superAdmin: str
    newSuperAdmin: str | None = None
    kycAddress: str
    isPaused: bool
    metadata: Dict[str, str]
    token_metadata: Dict[str, TokenMetadata]
    total_supply: Dict[str, str]
    userChunkLedger: Dict[str, UserChunkLedger]
    snapshotLedger: List[SnapshotLedgerItem]
    ledger: List[LedgerItem]
    operators: List[Operator]
