# generated by DipDup 8.4.2; relaxed for TZKT JSON (token_watcher / dynamic indexes)

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class TokenMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token_id: str
    token_info: Dict[str, str]


class UserChunkLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chunkCounter: str
    snapshotCounter: str


class Key(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nat_0: str
    address: str
    nat_1: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nat: str
    timestamp: str


class SnapshotLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: Dict[str, Value]


class Key1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    owner: str
    token_id: str


class LedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key1
    value: str


class Key2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address_0: str
    address_1: str
    nat: str


class Operator(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key2
    value: Dict[str, Any]


class BaseTokenStorage(BaseModel):
    """RWA / watcher FA2 layout; optional fields — TZKT may send big map ids (int) or expanded data."""

    model_config = ConfigDict(
        extra="ignore",
    )

    superAdmin: str | None = None
    newSuperAdmin: str | None = None
    kycAddress: str | None = None
    isPaused: bool | None = None
    total_supply: Dict[str, str] | str | None = None
    userChunkLedger: Dict[str, UserChunkLedger] | int | None = None
    snapshotLedger: List[SnapshotLedgerItem] | None = None

    admin: str | None = None
    governanceAddress: str | None = None
    totalSupply: str | None = None
    whitelistContracts: int | Dict[str, Any] | None = None

    metadata: int | Dict[str, Any] | None = None
    token_metadata: int | Dict[str, Any] | None = None
    ledger: int | List[LedgerItem] | None = None
    operators: int | List[Operator] | None = None
