# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PauseKycRegistrarParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kycRegistrarAddress: str
    pauseBool: bool
    actionToPause: str


class PauseKycRegistrarParameter(RootModel[List[PauseKycRegistrarParameterItem]]):
    root: List[PauseKycRegistrarParameterItem]
