# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field, RootModel


class PermitSetMemberItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    updateType: str
    memberAddress: str
    membershipTier: str


class Action(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitSetMember: List[PermitSetMemberItem]


class AddMemberKycItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memberAddress: str
    country: str
    region: str
    investorType: str


class SetMemberKycAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    addMemberKyc: List[AddMemberKycItem]


class UpdateMemberKycItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memberAddress: str
    country: str | None = None
    region: str | None = None
    investorType: str | None = None
    expireAt: str | None = None


class SetMemberKycAction1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    updateMemberKyc: List[UpdateMemberKycItem]


class SetMemberKycAction2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    removeMemberKyc: List[str]


class PermitSetMemberKyc(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    setMemberKycAction: SetMemberKycAction | SetMemberKycAction1 | SetMemberKycAction2
    field_unit: Dict[str, Any] = Field(..., alias="_unit")


class Action1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitSetMemberKyc: PermitSetMemberKyc


class PermitFreezeMember(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memberAddressList: List[str]
    freeze: bool


class Action2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitFreezeMember: PermitFreezeMember


class PermitSetPermitExpiryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userAddress: str
    expirySeconds: str
    permitHash: str | None = None


class Action3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitSetPermitExpiry: List[PermitSetPermitExpiryItem]


class PermitAndExecuteParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userPublicKey: str
    userSignature: str
    action: Action | Action1 | Action2 | Action3
    deadline: str


class PermitAndExecuteParameter(RootModel[List[PermitAndExecuteParameterItem]]):
    root: List[PermitAndExecuteParameterItem]
