# generated by DipDup 8.2.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class SetKycRegistrarParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    kycRegistrarAddress: str
    kycAdminAddresses: List[str]
