# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class SetMembershipTierDiscountParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    updateType: str
    membershipTierName: str
    discountName: str
    discountValue: str


class SetMembershipTierDiscountParameter(
    RootModel[List[SetMembershipTierDiscountParameterItem]]
):
    root: List[SetMembershipTierDiscountParameterItem]
