# generated by DipDup 8.2.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field


class AddNewCountryTransferRuleItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    whitelistCountries: List[str]
    blacklistCountries: List[str]
    sendingFrozen: bool
    receivingFrozen: bool


class SetCountryTransferRuleAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addNewCountryTransferRule: List[AddNewCountryTransferRuleItem]


class FreezeReceivingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    freezeBool: bool


class SetCountryTransferRuleAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    freezeReceiving: List[FreezeReceivingItem]


class FreezeSendingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    freezeBool: bool


class SetCountryTransferRuleAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    freezeSending: List[FreezeSendingItem]


class UpdateBlacklistCountry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    updateType: str
    countrySet: List[str]


class SetCountryTransferRuleAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateBlacklistCountries: List[UpdateBlacklistCountry]


class UpdateWhitelistCountry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    updateType: str
    countrySet: List[str]


class SetCountryTransferRuleAction4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateWhitelistCountries: List[UpdateWhitelistCountry]


class SetCountryTransferRuleParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    setCountryTransferRuleAction: (
        SetCountryTransferRuleAction
        | SetCountryTransferRuleAction1
        | SetCountryTransferRuleAction2
        | SetCountryTransferRuleAction3
        | SetCountryTransferRuleAction4
    )
    field_unit: Dict[str, Any] = Field(..., alias='_unit')
