# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field


class AddMemberKycItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memberAddress: str
    country: str
    region: str
    investorType: str


class SetMemberKycAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    addMemberKyc: List[AddMemberKycItem]


class SetMemberKycAction1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    removeMemberKyc: List[str]


class UpdateMemberKycItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memberAddress: str
    country: str | None = None
    region: str | None = None
    investorType: str | None = None
    expireAt: str | None = None


class SetMemberKycAction2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    updateMemberKyc: List[UpdateMemberKycItem]


class SetMemberKycParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    setMemberKycAction: SetMemberKycAction | SetMemberKycAction1 | SetMemberKycAction2
    field_unit: Dict[str, Any] = Field(..., alias="_unit")
