# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class SetMembershipTierParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    updateType: str
    kycRegistrarAddress: str
    membershipTierName: str


class SetMembershipTierParameter(RootModel[List[SetMembershipTierParameterItem]]):
    root: List[SetMembershipTierParameterItem]
