# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class SetMemberParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    updateType: str
    memberAddress: str
    membershipTier: str


class SetMemberParameter(RootModel[List[SetMemberParameterItem]]):
    root: List[SetMemberParameterItem]
