# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class SetRegistrarAdminParameterItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateType: str
    adminAddress: str
    kycRegistrarAddress: str


class SetRegistrarAdminParameter(RootModel[List[SetRegistrarAdminParameterItem]]):
    root: List[SetRegistrarAdminParameterItem]
