# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class AddMemberItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    memberAddress: str
    country: str
    region: str
    investorType: str


class SetMemberParameter1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addMember: List[AddMemberItem]


class SetMemberParameter2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    removeMember: List[str]


class UpdateMemberItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    memberAddress: str
    country: str | None = None
    region: str | None = None
    investorType: str | None = None
    expireAt: str | None = None


class SetMemberParameter3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateMember: List[UpdateMemberItem]


class SetMemberParameter(
    RootModel[SetMemberParameter1 | SetMemberParameter2 | SetMemberParameter3]
):
    root: SetMemberParameter1 | SetMemberParameter2 | SetMemberParameter3
