# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class AddNewCountryTransferRuleItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    whitelistCountries: List[str]
    blacklistCountries: List[str]
    sendingFrozen: bool
    receivingFrozen: bool


class SetCountryTransferRuleParameter1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addNewCountryTransferRule: List[AddNewCountryTransferRuleItem]


class FreezeReceivingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    freezeBool: bool


class SetCountryTransferRuleParameter2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    freezeReceiving: List[FreezeReceivingItem]


class FreezeSendingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    freezeBool: bool


class SetCountryTransferRuleParameter3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    freezeSending: List[FreezeSendingItem]


class UpdateBlacklistCountry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    updateType: str
    countrySet: List[str]


class SetCountryTransferRuleParameter4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateBlacklistCountries: List[UpdateBlacklistCountry]


class UpdateWhitelistCountry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: str
    updateType: str
    countrySet: List[str]


class SetCountryTransferRuleParameter5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateWhitelistCountries: List[UpdateWhitelistCountry]


class SetCountryTransferRuleParameter(
    RootModel[
        SetCountryTransferRuleParameter1
        | SetCountryTransferRuleParameter2
        | SetCountryTransferRuleParameter3
        | SetCountryTransferRuleParameter4
        | SetCountryTransferRuleParameter5
    ]
):
    root: (
        SetCountryTransferRuleParameter1
        | SetCountryTransferRuleParameter2
        | SetCountryTransferRuleParameter3
        | SetCountryTransferRuleParameter4
        | SetCountryTransferRuleParameter5
    )
