# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class SetValidInputParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inputType: str
    values: List[str]
