# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Key(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    string_0: str
    string_1: str


class MembershipTierLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: str


class KycRegistrarLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    kycAdmins: List[str]
    membersVerified: str
    createdAt: str
    setMemberKycIsPaused: bool
    freezeMemberIsPaused: bool
    unfreezeMemberIsPaused: bool


class CountryTransferRuleLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    whitelistCountries: List[str]
    blacklistCountries: List[str]
    sendingFrozen: bool
    receivingFrozen: bool


class MemberKycLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    country: str
    region: str
    investorType: str
    expireAt: str
    frozen: bool
    kycRegistrar: str


class KycStorage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    superAdmin: str
    newSuperAdmin: str | None = None
    metadata: Dict[str, str]
    pauseLedger: Dict[str, bool]
    membershipTierLedger: List[MembershipTierLedgerItem]
    memberLedger: Dict[str, str]
    whitelistLedger: Dict[str, Dict[str, Any]]
    blacklistLedger: Dict[str, Dict[str, Any]]
    validInputLedger: Dict[str, List[str]]
    kycRegistrarLedger: Dict[str, KycRegistrarLedger]
    countryTransferRuleLedger: Dict[str, CountryTransferRuleLedger]
    memberKycLedger: Dict[str, MemberKycLedger]
    enableKyc: bool
    enableMembership: bool
    lambdaLedger: Dict[str, str]
