# generated by DipDup 8.4.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permitDefaultExpiryDuration: str
    permitMaxExpiryDuration: str


class Key(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address: str
    string: str


class MembershipTierDiscountLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key
    value: Dict[str, str]


class Key1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address_0: str
    address_1: str


class MemberLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key1
    value: str


class KycRegistrarLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    membersVerified: str
    createdAt: str
    setMemberIsPaused: bool
    setMemberKycIsPaused: bool
    freezeMemberIsPaused: bool
    setRegistrarAdminIsPaused: bool


class CountryTransferRuleLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    whitelistCountries: List[str]
    blacklistCountries: List[str]
    sendingFrozen: bool
    receivingFrozen: bool


class MemberKycLedger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    country: str
    region: str
    investorType: str
    expireAt: str
    frozen: bool
    kycRegistrar: str


class Key2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address: str
    bytes: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    registeredAt: str
    deadline: str


class PermitsLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key2
    value: Value


class PermitsExpiryLedgerItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Key2
    value: str


class KycStorage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    superAdmin: str
    newSuperAdmin: str | None = None
    metadata: Dict[str, str]
    config: Config
    pauseLedger: Dict[str, bool]
    membershipTierLedger: Dict[str, List[str]]
    membershipTierDiscountLedger: List[MembershipTierDiscountLedgerItem]
    memberLedger: List[MemberLedgerItem]
    memberRegistrarLedger: Dict[str, List[str]]
    whitelistLedger: Dict[str, Dict[str, Any]]
    blacklistLedger: Dict[str, Dict[str, Any]]
    validInputLedger: Dict[str, List[str]]
    kycRegistrarLedger: Dict[str, KycRegistrarLedger]
    kycAdminRegistrarLedger: Dict[str, str]
    countryTransferRuleLedger: Dict[str, CountryTransferRuleLedger]
    memberKycLedger: Dict[str, MemberKycLedger]
    enableKyc: bool
    enableMembership: bool
    lambdaLedger: Dict[str, str]
    permitsLedger: List[PermitsLedgerItem]
    permitsCounterLedger: Dict[str, str]
    permitsExpiryLedger: List[PermitsExpiryLedgerItem]
    userPermitsExpiryLedger: Dict[str, str]
