# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class PartialPurchase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    listingId: str
    amount: str


class PurchaseParameter1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    partialPurchase: PartialPurchase


class PurchaseParameter2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    quickBuyPurchase: str


class PurchaseParameter(RootModel[PurchaseParameter1 | PurchaseParameter2]):
    root: PurchaseParameter1 | PurchaseParameter2
