# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class SetUserRolesParameterItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: str
    userAddress: str
    contractAddress: str
    updateType: str


class SetUserRolesParameter(RootModel[List[SetUserRolesParameterItem]]):
    root: List[SetUserRolesParameterItem]
