# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TransferParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    receiverAddress: str
    tokenContractAddress: str
    tokenAmount: str
    tokenType: str
    tokenId: str
