# generated by DipDup 8.4.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class ListItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    configName: str
    configNewValue: str


class UpdateConfigParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    list: List[ListItem]
    address: str
